kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-cm
  annotations:
    reloader.stakater.com/match: "true"
data:
  MERCURY_THEME_URL: https://vc3prerelease.blob.core.windows.net/packages/client-app-0.0.4-pr-128-b9ee85bc.zip
  MERCURY_THEME_LOCATION: /mnt/cms-content/Themes/B2B-store
  ASSETS_URL: https://vcbacpac.blob.core.windows.net/dac-packages/webstore_assets_4.zip
  ASSETS_LOCATION: /mnt/cms-content/assets
  modules.json: |
   [
    {
      "Id": "VirtoCommerce.Core",
      "Repository": "VirtoCommerce/vc-module-core",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-core/releases/download/3.200.0/VirtoCommerce.Core_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.AzureSearch",
      "Repository": "VirtoCommerce/vc-module-azure-search",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-azure-search/releases/download/3.203.0/VirtoCommerce.AzureSearch_3.203.0.zip"
    },
    {
      "Id": "VirtoCommerce.Cart",
      "Repository": "VirtoCommerce/vc-module-cart",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-cart/releases/download/3.201.0/VirtoCommerce.Cart_3.201.0.zip"
    },
    {
      "Id": "VirtoCommerce.Catalog",
      "Repository": "VirtoCommerce/vc-module-catalog",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-catalog/releases/download/3.210.0/VirtoCommerce.Catalog_3.210.0.zip"
    },
    {
      "Id": "VirtoCommerce.Content",
      "Repository": "VirtoCommerce/vc-module-content",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-content/releases/download/3.200.0/VirtoCommerce.Content_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.Customer",
      "Repository": "VirtoCommerce/vc-module-customer",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-customer/releases/download/3.201.0/VirtoCommerce.Customer_3.201.0.zip"
    },
    {
      "Id": "VirtoCommerce.ElasticSearch",
      "Repository": "VirtoCommerce/vc-module-elastic-search",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-elastic-search/releases/download/3.203.0/VirtoCommerce.ElasticSearch_3.203.0.zip"
    },
    {
      "Id": "VirtoCommerce.ExperienceApi",
      "Repository": "VirtoCommerce/vc-module-experience-api",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-experience-api/releases/download/3.209.0/VirtoCommerce.ExperienceApi_3.209.0.zip"
    },
    {
      "Id": "VirtoCommerce.ProfileExperienceApiModule",
      "Repository": "VirtoCommerce/vc-module-profile-experience-api",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-profile-experience-api/releases/download/3.205.0/VirtoCommerce.ProfileExperienceApiModule_3.205.0.zip"
    },
    {
      "Id": "VirtoCommerce.Export",
      "Repository": "VirtoCommerce/vc-module-export",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-export/releases/download/3.200.0/VirtoCommerce.Export_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.ImageTools",
      "Repository": "VirtoCommerce/vc-module-image-tools",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-image-tools/releases/download/3.200.0/VirtoCommerce.ImageTools_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.Inventory",
      "Repository": "VirtoCommerce/vc-module-inventory",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-inventory/releases/download/3.202.0/VirtoCommerce.Inventory_3.202.0.zip"
    },
    {
      "Id": "VirtoCommerce.LuceneSearch",
      "Repository": "VirtoCommerce/vc-module-lucene-search",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-lucene-search/releases/download/3.203.0/VirtoCommerce.LuceneSearch_3.203.0.zip"
    },
    {
      "Id": "VirtoCommerce.Marketing",
      "Repository": "VirtoCommerce/vc-module-marketing",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-marketing/releases/download/3.200.0/VirtoCommerce.Marketing_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.Notifications",
      "Repository": "VirtoCommerce/vc-module-notification",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-notification/releases/download/3.201.0/VirtoCommerce.Notifications_3.201.0.zip"
    },
    {
      "Id": "VirtoCommerce.Orders",
      "Repository": "VirtoCommerce/vc-module-order",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-order/releases/download/3.204.0/VirtoCommerce.Orders_3.204.0.zip"
    },
    {
      "Id": "VirtoCommerce.Payment",
      "Repository": "VirtoCommerce/vc-module-payment",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-payment/releases/download/3.202.0/VirtoCommerce.Payment_3.202.0.zip"
    },
    {
      "Id": "VirtoCommerce.Pricing",
      "Repository": "VirtoCommerce/vc-module-pricing",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-pricing/releases/download/3.203.0/VirtoCommerce.Pricing_3.203.0.zip"
    },
    {
      "Id": "VirtoCommerce.Search",
      "Repository": "VirtoCommerce/vc-module-search",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-search/releases/download/3.205.0/VirtoCommerce.Search_3.205.0.zip"
    },
    {
      "Id": "VirtoCommerce.Shipping",
      "Repository": "VirtoCommerce/vc-module-shipping",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-shipping/releases/download/3.200.0/VirtoCommerce.Shipping_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.Sitemaps",
      "Repository": "VirtoCommerce/vc-module-sitemaps",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-sitemaps/releases/download/3.201.0/VirtoCommerce.Sitemaps_3.201.0.zip"
    },
    {
      "Id": "VirtoCommerce.Store",
      "Repository": "VirtoCommerce/vc-module-store",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-store/releases/download/3.203.0/VirtoCommerce.Store_3.203.0.zip"
    },
    {
      "Id": "VirtoCommerce.Subscription",
      "Repository": "VirtoCommerce/vc-module-subscription",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-subscription/releases/download/3.200.0/VirtoCommerce.Subscription_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.Tax",
      "Repository": "VirtoCommerce/vc-module-tax",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-tax/releases/download/3.200.0/VirtoCommerce.Tax_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.CustomerReviews",
      "Repository": "VirtoCommerce/vc-module-customer-review",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-customer-review/releases/download/3.203.0/VirtoCommerce.CustomerReviews_3.203.0.zip"
    },
    {
      "Id": "VirtoCommerce.AuthorizeNet",
      "Repository": "VirtoCommerce/vc-module-Authorize.Net",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-Authorize.Net/releases/download/3.201.0/VirtoCommerce.AuthorizeNet_3.201.0.zip"
    },
    {
      "Id": "VirtoCommerce.AvalaraTax",
      "Repository": "VirtoCommerce/vc-module-avatax",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-avatax/releases/download/3.200.0/VirtoCommerce.AvalaraTax_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.CatalogPersonalization",
      "Repository": "VirtoCommerce/vc-module-catalog-personalization",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-catalog-personalization/releases/download/3.200.0/VirtoCommerce.CatalogPersonalization_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.CatalogPublishing",
      "Repository": "VirtoCommerce/vc-module-catalog-publishing",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-catalog-publishing/releases/download/3.200.0/VirtoCommerce.CatalogPublishing_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.CatalogCsvImportModule",
      "Repository": "VirtoCommerce/vc-module-catalog-csv-import",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-catalog-csv-import/releases/download/3.200.0/VirtoCommerce.CatalogCsvImportModule_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.BulkActionsModule",
      "Repository": "VirtoCommerce/vc-module-bulk-actions",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-bulk-actions/releases/download/3.200.0/VirtoCommerce.BulkActionsModule_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.Quote",
      "Repository": "VirtoCommerce/vc-module-quote",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-quote/releases/download/3.200.0/VirtoCommerce.Quote_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.DynamicAssociations",
      "Repository": "VirtoCommerce/vc-module-dynamic-associations",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-dynamic-associations/releases/download/3.200.0/VirtoCommerce.DynamicAssociationsModule_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.WebHooks",
      "Repository": "VirtoCommerce/vc-module-webhooks",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-webhooks/releases/download/3.200.0/VirtoCommerce.WebHooks_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.AzureBlobAssets",
      "Repository": "VirtoCommerce/vc-module-azureblob-assets",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-azureblob-assets/releases/download/3.200.0/VirtoCommerce.AzureBlobAssets_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.FileSystemAssets",
      "Repository": "VirtoCommerce/vc-module-filesystem-assets",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-filesystem-assets/releases/download/3.200.0/VirtoCommerce.FileSystemAssets_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.Assets",
      "Repository": "VirtoCommerce/vc-module-assets",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-assets/releases/download/3.200.0/VirtoCommerce.Assets_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.PageBuilderModule",
      "Repository": "VirtoCommerce/vc-module-pagebuilder",
      "PackageUrl": "https://rnd4pb.blob.core.windows.net/composer/VirtoCommerce.PageBuilderModule_3.201.0_templates_006.zip"
    }
   ]
