apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ingress-https.yaml
- deployment-cm.yaml
- platform-cm.yaml
- platform-deploy.yaml
- platform-secrets.yaml

resources:
- ../../common-base/platform
- ../../common-base/page-builder
- storefront-cm.yaml
- storefront-deploy.yaml
- storefront-service.yaml
- storage.yaml

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: ghcr.io/virtocommerce/platform
  newTag: 3.215.0-master-cafae536
- name: docker.pkg.github.com/virtocommerce/vc-storefront/storefront
  newName: ghcr.io/virtocommerce/storefront
  newTag: 6.1.0-alpha.886-st-2038-seoinfos-d1b8d3a0
- name: ghcr.io/virtocommerce/page-builder
  newName: ghcr.io/virtocommerce/page-builder
  newTag: 0.0.0
