apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ingress-https.yaml
- deployment-cm.yaml
- platform-cm.yaml
- platform-deploy.yaml
- platform-secrets.yaml
resources:
- ../../common-base/platform
- marketing-deploy.yaml
- marketing-ingress.yaml


images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: ghcr.io/virtocommerce/platform
  newTag: 3.200.0-alpha.12236-net6-e3579c53

- name: ghcr.io/virtocommerce/platform-marketing
  newName: ghcr.io/virtocommerce/platform-marketing
  newTag: 0.0.115

