kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-cm
data:
  ELECTRONICS_THEME_URL: https://github.com/VirtoCommerce/vc-theme-default/releases/download/2.1.13/vc-theme-default-2.1.13.zip
  ELECTRONICS_THEME_LOCATION: /mnt/cms-content/Themes/Electronics
  B2B_THEME_URL: https://github.com/VirtoCommerce/vc-theme-b2b/releases/download/3.0.8/vc-b2b-theme-3.0.8.zip
  B2B_THEME_LOCATION: /mnt/cms-content/Themes/B2B-store
  ASSETS_URL: https://vcbacpac.blob.core.windows.net/dac-packages/webstore_assets_4.zip
  ASSETS_LOCATION: /mnt/cms-content/assets
  modules.json: |
   [    
    {
      "Id": "VirtoCommerce.AuthorizeNet",
      "Repository": "VirtoCommerce/vc-module-Authorize.Net",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-Authorize.Net/releases/download/3.4.0/VirtoCommerce.AuthorizeNet_3.4.0.zip"
    },
    {
      "Id": "VirtoCommerce.AzureSearch",
      "Repository": "VirtoCommerce/vc-module-azure-search",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.AzureSearch_3.10.0-pr-23.zip"
    },
    {
      "Id": "VirtoCommerce.AvalaraTax",
      "Repository": "VirtoCommerce/vc-module-avatax",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-avatax/releases/download/3.4.0/VirtoCommerce.AvalaraTax_3.4.0.zip"
    },
    {
      "Id": "VirtoCommerce.BulkActionsModule",
      "Repository": "VirtoCommerce/vc-module-bulk-actions",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-bulk-actions/releases/download/3.3.0/VirtoCommerce.BulkActionsModule_3.3.0.zip"
    },
    {
      "Id": "VirtoCommerce.Cart",
      "Repository": "VirtoCommerce/vc-module-cart",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.21.0-pr-89.zip"
    },
    {
      "Id": "VirtoCommerce.CatalogPersonalization",
      "Repository": "VirtoCommerce/vc-module-catalog-personalization",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-catalog-personalization/releases/download/3.9.0/VirtoCommerce.CatalogPersonalization_3.9.0.zip"
    },
    {
      "Id": "VirtoCommerce.CatalogPublishing",
      "Repository": "VirtoCommerce/vc-module-catalog-publishing",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-catalog-publishing/releases/download/3.8.0/VirtoCommerce.CatalogPublishing_3.8.0.zip"
    },
    {
      "Id": "VirtoCommerce.PageBuilderModule",
      "Repository": "VirtoCommerce/vc-module-pagebuilder",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-pagebuilder/releases/download/3.10.5/VirtoCommerce.PageBuilderModule_3.10.5.zip"
    },
    {
      "Id": "VirtoCommerce.CatalogCsvImportModule",
      "Repository": "VirtoCommerce/vc-module-catalog-csv-import",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogCsvImportModule_3.26.0-pr-85.zip"
    },
    {
      "Id": "VirtoCommerce.Contentful",
      "Repository": "VirtoCommerce/vc-module-contentful",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-contentful/releases/download/3.0.1-preview/VirtoCommerce.Contentful_3.0.1-preview.zip"
    },
    
    {
      "Id": "VirtoCommerce.Quote",
      "Repository": "VirtoCommerce/vc-module-quote",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-quote/releases/download/3.15.0/VirtoCommerce.Quote_3.15.0.zip"
    },
    {
      "Id": "VirtoCommerce.DynamicAssociations",
      "Repository": "VirtoCommerce/vc-module-dynamic-associations",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.DynamicAssociationsModule_3.7.0-pr-23.zip"
    },
    {
      "Id": "VirtoCommerce.Core",
      "Repository": "VirtoCommerce/vc-module-core",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.21.0-pr-191.zip"
    },
    {
    "Id": "VirtoCommerce.ExperienceApi",
    "Repository": "VirtoCommerce/vc-module-experience-api",
    "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ExperienceApi_1.28.0-pr-202.zip"
    },
    {
      "Id": "VirtoCommerce.Customer",
      "Repository": "VirtoCommerce/vc-module-customer",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.30.0-pr-152.zip"
    },
    {
      "Id": "VirtoCommerce.Catalog",
      "Repository": "VirtoCommerce/vc-module-catalog",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-catalog/releases/download/3.62.0/VirtoCommerce.Catalog_3.62.0.zip"
    },
    {
      "Id": "VirtoCommerce.Content",
      "Repository": "VirtoCommerce/vc-module-content",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.12.0-pr-93.zip"
    },
    {
      "Id": "VirtoCommerce.ElasticSearch",
      "Repository": "VirtoCommerce/vc-module-elastic-search",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ElasticSearch_3.8.0-pr-29.zip"
    },
    {
      "Id": "VirtoCommerce.Export",
      "Repository": "VirtoCommerce/vc-module-export",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Export_3.14.0-pr-60.zip"
    },
    {
      "Id": "VirtoCommerce.ImageTools",
      "Repository": "VirtoCommerce/vc-module-image-tools",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-image-tools/releases/download/3.12.0/VirtoCommerce.ImageTools_3.12.0.zip"
    },
    {
      "Id": "VirtoCommerce.Inventory",
      "Repository": "VirtoCommerce/vc-module-inventory",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-inventory/releases/download/3.17.0/VirtoCommerce.Inventory_3.17.0.zip"
    },
    {
      "Id": "VirtoCommerce.Marketing",
      "Repository": "VirtoCommerce/vc-module-marketing",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-marketing/releases/download/3.23.0/VirtoCommerce.Marketing_3.23.0.zip"
    },
    {
      "Id": "VirtoCommerce.Notifications",
      "Repository": "VirtoCommerce/vc-module-notification",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-notification/releases/download/3.18.0/VirtoCommerce.Notifications_3.18.0.zip"
    },
    {
      "Id": "VirtoCommerce.Orders",
      "Repository": "VirtoCommerce/vc-module-order",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.36.0-pr-254.zip"
    },
    {
      "Id": "VirtoCommerce.Payment",
      "Repository": "VirtoCommerce/vc-module-payment",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-payment/releases/download/3.7.0/VirtoCommerce.Payment_3.7.0.zip"
    },
    {
      "Id": "VirtoCommerce.Pricing",
      "Repository": "VirtoCommerce/vc-module-pricing",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-pricing/releases/download/3.21.0/VirtoCommerce.Pricing_3.21.0.zip"
    },
    {
      "Id": "VirtoCommerce.Search",
      "Repository": "VirtoCommerce/vc-module-search",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-search/releases/download/3.15.0/VirtoCommerce.Search_3.15.0.zip"
    },
    {
      "Id": "VirtoCommerce.Shipping",
      "Repository": "VirtoCommerce/vc-module-shipping",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-shipping/releases/download/3.6.0/VirtoCommerce.Shipping_3.6.0.zip"
    },
    {
      "Id": "VirtoCommerce.Sitemaps",
      "Repository": "VirtoCommerce/vc-module-sitemaps",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-sitemaps/releases/download/3.7.0/VirtoCommerce.Sitemaps_3.7.0.zip"
    },
    {
      "Id": "VirtoCommerce.Store",
      "Repository": "VirtoCommerce/vc-module-store",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Store_3.22.0-pr-85.zip"
    },
    {
      "Id": "VirtoCommerce.Subscription",
      "Repository": "VirtoCommerce/vc-module-subscription",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-subscription/releases/download/3.11.0/VirtoCommerce.Subscription_3.11.0.zip"
    },
    {
      "Id": "VirtoCommerce.Tax",
      "Repository": "VirtoCommerce/vc-module-tax",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-tax/releases/download/3.6.0/VirtoCommerce.Tax_3.6.0.zip"
    },
    {
      "Id": "VirtoCommerce.EventBus",
      "Repository": "VirtoCommerce/vc-module-event-bus",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-event-bus/releases/download/1.1.0/VirtoCommerce.EventBus_1.1.0.zip"
    },
    {
      "Id": "VirtoCommerce.WebHooks",
      "Repository": "VirtoCommerce/vc-module-webhooks",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-webhooks/releases/download/3.4.0/VirtoCommerce.WebHooks_3.4.0.zip"
    },
    {
      "Id": "VirtoCommerce.FeatureManagement",
      "Repository": "VirtoCommerce/vc-module-feature-flags",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-feature-flags/releases/download/3.0.0/VirtoCommerce.FeatureManagement_3.0.0.zip"
    },
    {
      "Id": "VirtoCommerce.PriceExportImport",
      "Repository": "VirtoCommerce/vc-module-price-export-import",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-price-export-import/releases/download/1.1.0/VirtoCommerce.PriceExportImport_1.1.0.zip"
    }
   ]
