apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ingress-https.yaml
- deployment-cm.yaml
- platform-cm.yaml
- platform-deploy.yaml
- platform-secrets.yaml
resources:
- ../../common-base/platform

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: ghcr.io/virtocommerce/platform
  newTag: 3.218.0-alpha.12351-dev-6109f854
- name: ghcr.io/virtocommerce/demo-xapi-app
  newName: ghcr.io/virtocommerce/demo-xapi-app
  newTag: 1.0.0-alpha.16-vds-2423
- name: docker.pkg.github.com/virtocommerce/vc-storefront/storefront
  newName: ghcr.io/virtocommerce/vc-demo-storefront/demo-storefront
  newTag: 1.12.0-master-9b6ba2d6
