apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ingress-https.yaml
- deployment-cm.yaml
- platform-cm.yaml
- platform-deploy.yaml
- platform-secrets.yaml
- storefront-cm.yaml
- storefront-deploy.yaml

resources:
- ../../common-base/platform
- ../../common-base/storefront

images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: ghcr.io/virtocommerce/platform
  newTag: 3.223.0-alpha.12369-dev-996cccd2
- name: docker.pkg.github.com/virtocommerce/vc-storefront/storefront
  newName: ghcr.io/virtocommerce/storefront
  newTag: 5.9.0-alpha.816-dev-a4ca11f9
