apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ingress-https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-url: "https://vcplatform-platform.dev.govirto.com/api/platform/security/users/admin"
    nginx.ingress.kubernetes.io/auth-response-headers: "api_key"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "16"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:   
      - "$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com"
      secretName: $(VC_PLATFORM_SERVICE)-$(VC_NAMESPACE)-tls
  rules:
  - host: $(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com
    http:
      paths:
      - backend:
          serviceName: platform
          servicePort: 80
        path: /